name: Staging Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: connect ssh to staging server
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy to staging server
        run: ssh ec2-user@staging-patient-app.houseworksinc.co -o StrictHostKeyChecking=no 'bash -s' < deploy_scripts/deploy_staging.sh
